[package]
name = "cw-storage-gas-meter"
version = "0.1.0"
edition = "2021"
authors = ["yoisha <48324733+y-pakorn@users.noreply.github.com>"]
repository = "https://github.com/y-pakorn/cw-storage-gas-meter"

[dependencies]
cosmwasm-std = "1.0.0"

[dev-dependencies]
cw-storage-plus = "0.13.4"
